# Generated by Django 4.2.7 on 2025-11-06 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='conversatio_user_id_f77e9b_idx',
            old_name='conversations_user_id_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='conversatio_status_a7a90f_idx',
            old_name='conversations_status_b3c4d5_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='conversatio_user_id_56f168_idx',
            old_name='conversations_user_status_e6f7g8_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationanalysis',
            new_name='conversatio_convers_cbe17a_idx',
            old_name='conversations_conver_analysis_k2l3m4_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='conversatio_convers_4b968d_idx',
            old_name='conversations_conver_d5c7f1_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='conversatio_sender_69ddcd_idx',
            old_name='conversations_sender_a9b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='searchquery',
            new_name='conversatio_user_id_f1e4a2_idx',
            old_name='conversations_user_created_h9i0j1_idx',
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)]),
        ),
    ]
